server:
 port: 8201

spring:
 application:
  name: GDMS-Server-Search
 boot:
  admin:
   client:
    url: http://localhost:8401
    username: gdms
    password: gdmsadmin

eureka:
 instance:
  lease-renewal-interval-in-seconds: 20
 client:
  register-with-eureka: true
  fetch-registry: true
  instance-info-replication-interval-seconds: 30
  serviceUrl:
   defaultZone: http://gdms:graduationdesign@localhost:8001/register/eureka/

security:
 oauth2:
  resource:
   id: ${spring.application.name}
   user-info-uri: http://localhost:8301/auth/user

info:
 app:
  name: ${spring.application.name}
  description: "@project.description@"
  version: "@project.version@"

management:
 endpoints:
  web:
   exposure:
    include: '*'
 endpoint:
  health:
   show-details: ALWAYS
