server:
  port: 8301

spring:
  application:
    name: GDMS-Gateway
  boot:
    admin:
      client:
        url: http://54.234.98.178:8401
        username: gdms
        password: gdmsadmin

eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 30
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: http://gdms:graduationdesign@54.234.98.178:8001/register/eureka/

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  routes:
    auth:
      path: /auth/**
      serviceId: GDMS-Auth
      sensitiveHeaders: "*"
    search:
      path: /search/**
      serviceId: GDMS-Server-Search
      sensitiveHeaders: "*"
    notice:
      path: /notice/**
      serviceId: GDMS-Server-Notice
      sensitiveHeaders: "*"
    core:
      path: /core/**
      serviceId: GDMS-Server-Core
      sensitiveHeaders: "*"
  retryable: true
  ignored-services: "*"
  ribbon:
    eager-load:
      enabled: true

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
