server:
  port: 8203

spring:
  application:
    name: GDMS-Server-Core
  datasource:
    username: root
    password: graduationdesign
    url: jdbc:mysql://54.234.98.178:3306/gdms?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://54.234.98.178:27017
      database: gdms
  boot:
    admin:
      client:
        url: http://54.234.98.178:8401
        username: gdms
        password: gdmsadmin

eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 30
    serviceUrl:
      defaultZone: http://gdms:graduationdesign@54.234.98.178:8001/register/eureka/

security:
  oauth2:
    resource:
      id: ${spring.application.name}
      user-info-uri: http://54.234.98.178:8301/auth/user

info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
